### PR TITLE
chore: update functional view of connector

### PR DESCRIPTION
**Pull request by juliapampus**
Updates functional view of connector
- Transform IDS components from components to structured classifiers
- Aligns UML visualization of interfaces

### CODE REVIEW

**Comment by juliapampus** [comment]
Incorporated feedback from @HeinrichPet:
- removed self-description
- added data flow between ids protocol component
- resolved spelling mistakes

**Review by HeinrichPet — APPROVED** [review]

**Review by ssteinbuss — COMMENTED** [review]
Good work, this is an improvement. I have one question. Why is the self-description interface being removed?

**Comment by HeinrichPet** [comment]
@ssteinbuss Because it is part of the IDS protocol defined above. There should be no case where you use the self-description directly. Either you use the protocol via the connector or you use the metadata broker / federated catalog.

**Review by ssteinbuss — APPROVED** [review]

**Comment by ssteinbuss** [comment]
This is a substantial change that needs approval by the working group and the TSC before merging.

**Pull request merged**
